<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profile</name>
   <tag></tag>
   <elementGuidId>c1f40ced-a37a-412e-beb7-3e7486a5fc50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='app_top_area_nav_bar']/div/div/section[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a01a51e6-897d-414c-811c-512b22d0356f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/employee/Profile/Overview</value>
      <webElementGuid>80b91b78-738d-4ed3-b211-2d0efa083aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-sub-header__link</value>
      <webElementGuid>33bb47cd-da6e-43d6-9305-3305a52acc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Profile
                                        </value>
      <webElementGuid>f8bea0fe-a22e-4514-bcfe-cdd05308e501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_top_area_nav_bar&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/section[@class=&quot;site-sub-header__nav-container col-sm-8&quot;]/div[@class=&quot;site-sub-header__nav js-top-nav&quot;]/ul[@class=&quot;site-sub-header__nav-list unstyled-ul js-top-nav-list&quot;]/li[@class=&quot;site-sub-header__link-item&quot;]/a[@class=&quot;site-sub-header__link&quot;]</value>
      <webElementGuid>2b4b85a2-e248-46ea-9554-4e4c0de65ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='app_top_area_nav_bar']/div/div/section[2]/div/ul/li[2]/a</value>
      <webElementGuid>d36449be-02f8-401e-9a82-2d381b6ff9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Profile')]</value>
      <webElementGuid>3490984b-8045-420d-91e8-67640fa332f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::a[1]</value>
      <webElementGuid>30f46b37-adf0-41a8-8481-e4568d5b348c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KMS Technology Inc'])[1]/following::a[2]</value>
      <webElementGuid>56c5579f-3282-447e-bb3b-79170c98c387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits'])[1]/preceding::a[1]</value>
      <webElementGuid>ea3a6b4a-c7aa-447e-874b-6065ddc0202e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required Tasks'])[1]/preceding::a[2]</value>
      <webElementGuid>a30bd1f8-7129-48b6-b179-6fe2895ae212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profile']/parent::*</value>
      <webElementGuid>6bea906f-16db-490a-bcc7-d3eec4b2b0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/employee/Profile/Overview')]</value>
      <webElementGuid>7640e0f3-4e7a-4a01-9203-15c470cf7156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>ec954cef-60f8-4d4a-a883-eaed79f11088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/employee/Profile/Overview' and (text() = '
                                            Profile
                                        ' or . = '
                                            Profile
                                        ')]</value>
      <webElementGuid>6f6ddc5e-1eb0-4b7a-b82a-fe07cc369b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
