<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Education</name>
   <tag></tag>
   <elementGuidId>17307fb4-43dc-4067-8f76-256fc8a6763a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[5]/div/div/nav/ul/li/ul/li[12]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eee0eeef-cf8f-4e42-98b4-1318817a5338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education
        </value>
      <webElementGuid>9bb85772-cb84-4046-8e1a-6ef45b102862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container mobile-margin&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3&quot;]/nav[@class=&quot;en-section en-nav-list&quot;]/ul[@class=&quot;unstyled-ul&quot;]/li[@class=&quot;en-nav-list__item option-block active-option&quot;]/ul[@class=&quot;link-section unstyled-ul&quot;]/li[@class=&quot;link-section__item&quot;]/a[@class=&quot;&quot;]/span[@class=&quot;&quot;]</value>
      <webElementGuid>9f4c65ac-b434-4d81-a44b-80b869e5b0ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[5]/div/div/nav/ul/li/ul/li[12]/a/span[2]</value>
      <webElementGuid>92b2a311-1e49-48b6-85f5-a5938fdc0c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Licenses'])[2]/following::span[2]</value>
      <webElementGuid>c7b02fd8-d2c0-400f-941f-26b83d626191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificates'])[2]/following::span[4]</value>
      <webElementGuid>a6bd80b4-546b-4f35-a696-a718d9edc842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assets'])[2]/preceding::span[2]</value>
      <webElementGuid>37546e5b-ed1f-4d3c-bc44-ecf5089d7ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withholdings'])[2]/preceding::span[4]</value>
      <webElementGuid>a495850f-3799-4b6f-b585-3698181bbef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[12]/a/span[2]</value>
      <webElementGuid>9c095cf1-7d69-428e-ae5d-ef6ae873f5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Education
        ' or . = 'Education
        ')]</value>
      <webElementGuid>c401a487-2f53-401a-aaf0-4db329ff7a24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
