<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Graduation Date_GraduationDate</name>
   <tag></tag>
   <elementGuidId>7cd508c1-7167-45ef-a85c-1fbc9a5d4264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GraduationDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GraduationDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f27ccfc9-08cd-4e2a-bffc-73c10cbcc39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>701c883f-9b5f-4ae2-b89f-5f50e66162ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-input</value>
      <webElementGuid>ab5aca3f-fdf3-4927-b5fd-20fe30c0a4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GraduationDate</value>
      <webElementGuid>1a18fe07-4331-4d3f-a76b-211e822a31b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GraduationDate</value>
      <webElementGuid>413dd2a2-2256-45fc-a690-736c92a60e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>305f857b-512c-41c6-8513-0fbc935e6506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12/11/1998 12:00:00 AM</value>
      <webElementGuid>4f2eb7a0-29df-446a-8846-a19c849fbe01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GraduationDate&quot;)</value>
      <webElementGuid>47c43a4d-7417-4dde-81bd-87c756d233de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GraduationDate']</value>
      <webElementGuid>8dcc01bd-40dc-4331-880d-daf76fbd3db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditContainer']/div/div/div/form/div/div[4]/div/div/input</value>
      <webElementGuid>8d5ad12f-5802-41eb-aa30-ffe8a2bf3216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>744967a4-a24f-43a5-b1b2-2ee074f4363d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GraduationDate' and @name = 'GraduationDate' and @type = 'text']</value>
      <webElementGuid>470ae56c-d2ae-414f-884f-24e642e3d1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
